In [1]:
import pandas as pd

In [7]:
horizontal_well = pd.read_csv("../data/raw/train/000d7d20__horizontal_well.csv")
horizontal_well.head()
print(horizontal_well.columns.tolist())
print(horizontal_well.shape)
horizontal_well.head()

['MD', 'X', 'Y', 'Z', 'ANCC', 'ASTNU', 'ASTNL', 'EGFDU', 'EGFDL', 'BUDA', 'TVT', 'GR', 'TVT_input']
(5278, 13)

,MD,X,Y,Z,ANCC,ASTNU,ASTNL,EGFDU,EGFDL,BUDA,TVT,GR,TVT_input
0,11467.0,2983525.16,1069022.09,-9258.57,-9395.81,-9569.86,-9597.64,-9670.99,-9705.96,-9846.35,11236.02,115.692586,11236.02
1,11468.0,2983525.18,1069022.30,-9259.55,-9395.75,-9569.80,-9597.58,-9670.93,-9705.90,-9846.29,11237.05,115.584293,11237.05
2,11469.0,2983525.20,1069022.52,-9260.52,-9395.69,-9569.74,-9597.52,-9670.87,-9705.84,-9846.23,11238.09,135.446960,11238.09
3,11470.0,2983525.22,1069022.73,-9261.50,-9395.64,-9569.69,-9597.47,-9670.82,-9705.79,-9846.18,11239.12,140.401346,11239.12
4,11471.0,2983525.25,1069022.95,-9262.47,-9395.58,-9569.63,-9597.41,-9670.76,-9705.73,-9846.12,11240.15,111.270638,11240.15

In [8]:
hw_test = pd.read_csv("../data/raw/test/000d7d20__horizontal_well.csv")
print(hw_test.columns.tolist())
print(hw_test.shape)
hw_test.head()

['MD', 'X', 'Y', 'Z', 'GR', 'TVT_input']
(5278, 6)

        MD           X           Y        Z          GR  TVT_input
0  11467.0  2983525.16  1069022.09 -9258.57  115.692586   11236.02
1  11468.0  2983525.18  1069022.30 -9259.55  115.584293   11237.05
2  11469.0  2983525.20  1069022.52 -9260.52  135.446960   11238.09
3  11470.0  2983525.22  1069022.73 -9261.50  140.401346   11239.12
4  11471.0  2983525.25  1069022.95 -9262.47  111.270638   11240.15

In [9]:
print("train shape:", horizontal_well.shape, "| test shape:", hw_test.shape)
print("train TVT_input NaN count:", horizontal_well["TVT_input"].isna().sum())
print("test  TVT_input NaN count:", hw_test["TVT_input"].isna().sum() if "TVT_input" in hw_test.columns else "no col")

train shape: (5278, 13) | test shape: (5278, 6)
train TVT_input NaN count: 3836
test  TVT_input NaN count: 3836

In [5]:
typewell = pd.read_csv("../data/raw/train/000d7d20__typewell.csv")
typewell.head()

        TVT      GR Geology
0  11223.95  126.11     NaN
1  11224.45  128.22     NaN
2  11224.95  128.72     NaN
3  11225.45  128.12     NaN
4  11225.95  125.29     NaN

In [6]:
submission = pd.read_csv("../data/raw/sample_submission.csv")
submission.head()

              id  tvt
0  000d7d20_1442  0.0
1  000d7d20_1443  0.0
2  000d7d20_1444  0.0
3  000d7d20_1445  0.0
4  000d7d20_1446  0.0